name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/dev' && 'dev' }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Create .env file
      run: |
        cat <<EOF > .env
        PORT=${{ vars.PORT }}
        CUSTOM_MESSAGE=${{ vars.CUSTOM_MESSAGE }}
        EOF

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd sample_node/
          git pull origin ${{ github.ref_name }}
          npm install --omit=dev
          pm2 restart demo_api_server || pm2 start server.js --name "demo_api_server"
          sudo systemctl restart nginx
